In [3]:
#Medical Insurance Cost Prediction

In [4]:
import numpy as np
import pandas as pd

In [5]:
data=pd.read_csv('insurance.csv')

In [7]:
data.head(10)

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
5   31  female  25.740         0     no  southeast   3756.62160
6   46  female  33.440         1     no  southeast   8240.58960
7   37  female  27.740         3     no  northwest   7281.50560
8   37    male  29.830         2     no  northeast   6406.41070
9   60  female  25.840         0     no  northwest  28923.13692

In [11]:
data=data.drop('region',axis=1)

In [75]:
data

age  sex     bmi  children  smoker      charges
0      19    1  27.900         0       1  16884.92400
1      18    0  33.770         1       0   1725.55230
2      28    0  33.000         3       0   4449.46200
3      33    0  22.705         0       0  21984.47061
4      32    0  28.880         0       0   3866.85520
...   ...  ...     ...       ...     ...          ...
1333   50    0  30.970         3       0  10600.54830
1334   18    1  31.920         0       0   2205.98080
1335   18    1  36.850         0       0   1629.83350
1336   21    1  25.800         0       0   2007.94500
1337   61    1  29.070         0       1  29141.36030

[1338 rows x 6 columns]

In [14]:
data.shape

(1338, 6)

In [18]:
data.replace({'sex' :{'male':0,'female':1}},inplace=True)

data.replace({'smoker':{'yes':1,'no':0}},inplace=True)

In [19]:
data


age  sex     bmi  children  smoker      charges
0      19    1  27.900         0       1  16884.92400
1      18    0  33.770         1       0   1725.55230
2      28    0  33.000         3       0   4449.46200
3      33    0  22.705         0       0  21984.47061
4      32    0  28.880         0       0   3866.85520
...   ...  ...     ...       ...     ...          ...
1333   50    0  30.970         3       0  10600.54830
1334   18    1  31.920         0       0   2205.98080
1335   18    1  36.850         0       0   1629.83350
1336   21    1  25.800         0       0   2007.94500
1337   61    1  29.070         0       1  29141.36030

[1338 rows x 6 columns]

In [20]:
X=data.drop('charges',axis=1)
y=data['charges']

In [21]:
X

age  sex     bmi  children  smoker
0      19    1  27.900         0       1
1      18    0  33.770         1       0
2      28    0  33.000         3       0
3      33    0  22.705         0       0
4      32    0  28.880         0       0
...   ...  ...     ...       ...     ...
1333   50    0  30.970         3       0
1334   18    1  31.920         0       0
1335   18    1  36.850         0       0
1336   21    1  25.800         0       0
1337   61    1  29.070         0       1

[1338 rows x 5 columns]

In [22]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...     
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train,y_train,X_test,y_test=train_test_split(X,y,test_size=0.2)

In [25]:
X_train

age  sex     bmi  children  smoker
947    37    0  34.200         1       1
408    38    0  21.120         3       0
207    35    0  27.740         2       1
996    39    1  34.100         3       0
554    25    1  41.325         0       0
...   ...  ...     ...       ...     ...
1001   24    0  32.700         0       1
198    51    1  18.050         0       0
409    32    0  30.030         1       0
993    38    0  28.270         1       0
1333   50    0  30.970         3       0

[1070 rows x 5 columns]

In [26]:
X_test

947     39047.28500
408      6652.52880
207     20984.09360
996      7418.52200
554     17878.90068
           ...     
1001    34472.84100
198      9644.25250
409      4074.45370
993      5484.46730
1333    10600.54830
Name: charges, Length: 1070, dtype: float64

In [27]:
y_train

age  sex     bmi  children  smoker
1245   28    0  24.300         5       0
1055   55    0  27.645         0       0
979    36    1  29.920         0       0
1041   18    0  23.085         0       0
622    49    1  21.300         1       0
...   ...  ...     ...       ...     ...
61     25    0  33.660         4       0
668    62    0  32.015         0       1
1335   18    1  36.850         0       0
235    40    1  22.220         2       1
1254   34    1  27.720         0       0

[268 rows x 5 columns]

In [28]:
y_test

1245     5615.36900
1055    10594.50155
979      4889.03680
1041     1704.70015
622      9182.17000
           ...     
61       4504.66240
668     45710.20785
1335     1629.83350
235     19444.26580
1254     4415.15880
Name: charges, Length: 268, dtype: float64

In [50]:
from sklearn.preprocessing import StandardScaler

In [51]:
scalar=StandardScaler()

In [54]:
X_train=scalar.fit_transform(X_train)
y_train=scalar.transform(y_train)

C:\Users\Sanyukta S Phatate\.conda\envs\machineLearning\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


In [55]:
X_train

array([[-0.15675439, -0.98515688,  0.5748302 , -0.06421995,  1.97125461],
       [-0.08628078, -0.98515688, -1.55768182,  1.61176412, -0.50729114],
       [-0.29770161, -0.98515688, -0.47838293,  0.77377208,  1.97125461],
       ...,
       [-0.50912245, -0.98515688, -0.10503029, -0.06421995, -0.50729114],
       [-0.08628078, -0.98515688, -0.3919738 , -0.06421995, -0.50729114],
       [ 0.75940257, -0.98515688,  0.04822364,  1.61176412, -0.50729114]])

In [56]:
y_train

array([[ 2.80000000e+01,  4.81442508e-17,  2.43000000e+01,
         5.00000000e+00, -2.32420521e-17],
       [ 5.50000000e+01,  4.81442508e-17,  2.76450000e+01,
         3.07127117e-17, -2.32420521e-17],
       [ 3.60000000e+01,  1.00000000e+00,  2.99200000e+01,
         3.07127117e-17, -2.32420521e-17],
       ...,
       [ 1.80000000e+01,  1.00000000e+00,  3.68500000e+01,
         3.07127117e-17, -2.32420521e-17],
       [ 4.00000000e+01,  1.00000000e+00,  2.22200000e+01,
         2.00000000e+00,  1.00000000e+00],
       [ 3.40000000e+01,  1.00000000e+00,  2.77200000e+01,
         3.07127117e-17, -2.32420521e-17]])

In [58]:
import pickle
pickle.dump(scalar,open('scaling.pkl','wb'))

In [30]:
from sklearn.linear_model import LinearRegression

In [32]:
model=LinearRegression()

In [34]:
model.fit(X_train,X_test)

LinearRegression()

In [36]:
pred=model.predict(y_train)

In [45]:
df=pd.DataFrame({'Actual':y_test,'Predicted':pred})

In [46]:
print(df)

           Actual     Predicted
1245   5615.36900   4713.757584
1055  10594.50155  11044.408705
979    4889.03680   7001.006461
1041   1704.70015    214.116815
622    9182.17000   8114.315585
...           ...           ...
61     4504.66240   6382.675880
668   45710.20785  38123.720445
1335   1629.83350   4423.759289
235   19444.26580  30390.916552
1254   4415.15880   5840.842264

[268 rows x 2 columns]


In [48]:
model.predict([[18,1,30,0,0]])

C:\Users\Sanyukta S Phatate\.conda\envs\machineLearning\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([2408.42148174])

In [65]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error,accuracy_score

#print(accuracy_score(y_test,pred))

print(mean_absolute_error(y_test,pred))
print(mean_squared_error(y_test,pred))
print(np.sqrt(mean_squared_error(y_test,pred)))

4416.073107133562
42970537.11171071
6555.19161517882


In [68]:
pickle.dump(model,open('model.pkl','wb'))

In [70]:
pickle_model=pickle.load(open('model.pkl','rb'))

In [81]:
pickle_model.predict(X_train[1].reshape(1,-1))

C:\Users\Sanyukta S Phatate\.conda\envs\machineLearning\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-23497.36311706])

In [82]:
X_train[1]

array([-0.08628078, -0.98515688, -1.55768182,  1.61176412, -0.50729114])